<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Register</title>
  <link rel="stylesheet" href="styles.css" />
</head><style>
    * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Georgia', serif;
}

body {
  background-color: #f5f5f5;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding: 1rem;
}

.card {
  background-color: #ffffff;
  padding: 3rem 2.5rem;
  border-radius: 14px;
  box-shadow: 0 12px 24px rgba(0, 0, 0, 0.1);
  text-align: center;
  max-width: 500px;
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 1.75rem;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
  transform: translateY(-6px);
  box-shadow: 0 16px 32px rgba(0, 0, 0, 0.15);
}

.card h1 {
  font-size: 2.25rem;
  color: #333;
}

.card p {
  font-size: 1.1rem;
  color: #555;
  line-height: 1.7;
}

.card input {
  padding: 0.75rem 1rem;
  border-radius: 6px;
  border: 1px solid #ccc;
  font-size: 1rem;
  width: 100%;
  transition: border-color 0.3s ease;
}

.card input:focus {
  border-color: #ff7f50;
  outline: none;
}

.card button {
  background-color: #ff7f50;
  color: white;
  border: none;
  padding: 0.85rem 1rem;
  border-radius: 6px;
  font-size: 1.05rem;
  width: 100%;
  cursor: pointer;
  transition: background-color 0.3s ease, box-shadow 0.3s ease;
}

.card button:hover {
  background-color: #ff5722;
  box-shadow: 0 4px 12px rgba(255, 87, 34, 0.4);
}
.card form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.card input {
  padding: 0.75rem 1rem;
  border-radius: 6px;
  border: 1px solid #ccc;
  font-size: 1rem;
  width: 100%;
  transition: border-color 0.3s ease;
}

.card input:focus {
  border-color: #ff7f50;
  outline: none;
}

.card button {
  background-color: #ff7f50;
  color: white;
  border: none;
  padding: 0.85rem 1rem;
  border-radius: 6px;
  font-size: 1.05rem;
  width: 100%;
  cursor: pointer;
  transition: background-color 0.3s ease, box-shadow 0.3s ease;
}

.card button:hover {
  background-color: #ff5722;
  box-shadow: 0 4px 12px rgba(255, 87, 34, 0.4);
}


</style>
<body>
  <div class="card">
    <h1>Register</h1>
    <p>Please fill in the form to create an account.</p>
    <form>
      <input type="text" placeholder="Full Name" required />
      <input type="email" placeholder="Email Address" required />
      <input type="password" placeholder="Password" required />
      <button type="submit">Sign Up</button>
    </form>
  </div>
</body>
</html>

